### ISSUE TITLE
[ISSUE] Maximizing Window cuts off top of screen

### ISSUE THREAD

**Issue by kwadroke** [netrek/JavaNetrek#4]
Not sure about other OS's, but on Linux when you maximize the main game Window after the game is started, the top of the Window is cut off/hidden. It's about the height of the "window decoration"/top window bar.

Screenshots:

Regular Window:  
![Screenshot_2021-06-11_13-56-41](https://user-images.githubusercontent.com/3247032/121736343-0d8e6e80-cabd-11eb-9256-f372fe97c24d.png)

After Maximizing:  
![Screenshot_2021-06-11_13-57-11](https://user-images.githubusercontent.com/3247032/121736353-10895f00-cabd-11eb-9586-4a4e81b94d07.png)

**Comment by darrellroot** [comment]
This is fixed in version 1.0 which will be released in a few hours.  Thanks for the report!

**Comment by kwadroke** [comment]
Tested. Works great now. Thanks.
