### ISSUE TITLE
[ISSUE] Help Window text is cut off on the bottom

### ISSUE THREAD

**Issue by kwadroke** [netrek/JavaNetrek#5]
Text on Help Window is cut off (on Linux). Can't read the bottom line (at least). Might just to increase the Window size slightly.

Screenshot:
![Screenshot_2021-06-11_14-00-19](https://user-images.githubusercontent.com/3247032/121736879-c5bc1700-cabd-11eb-88b5-8a4cb2ddf4df.png)

**Comment by darrellroot** [comment]
This is fixed in version 1.0.0 which gets released in a few hours.  Thanks for the report!  This one was annoyingly hard to fix because I can't figure out where the bounds of the help window are being set.
